#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# manual install and download of Fckeditor
VERSION=2.6.11
URL="http://downloads.sourceforge.net/project/fckeditor/FCKeditor/${VERSION}/FCKeditor_${VERSION}.zip"

dl $URL /usr/local/src
